discharge_private:
  description: "Décharge Titan(s) PID (proxy khirale)"
  fields:
    device_id: {description: "ID principal", example: "6cd3be8315ef44c5cdfaa6d64cc23394"}
    power: {description: "Puissance W", example: 1000}
    soc_limit: {description: "SOC limite %", example: 10}

charge_private:
  description: "Charge Titan(s) PID"  
  fields:
    device_id: {example: "6cd3be8315ef44c5cdfaa6d64cc23394"}
    power: {example: 800}
    soc_limit: {example: 95}

stop_private:
  description: "Stop Titan(s) PID immédiat"
  fields:
    device_id: {example: "6cd3be8315ef44c5cdfaa6d64cc23394"}

